### ISSUE TITLE
萌典「广」釋義錯誤。

### ISSUE THREAD

**Issue by kunki** [audreyt/moedict-webkit#113]
「广」字是二一四部首之一，《說文解字》說像對剌高屋之形，和「宀」一樣都是房屋類漢字的重要部首。在對岸簡化漢字之前，「广」和「廣」根本沒絲毫干係。
《敎育部重編國語辭典》也收錄了此字：http://dict.revised.moe.edu.tw/cgi-bin/newDict/dict.sh?idx=dict.idx&cond=^%8E%F3$&pieceLen=50&fld=1&cat=&serial=4&recNo=0&op=&imgFont=1

讀音爲｜ㄢˇ而非ㄍㄨㄤˇ

釋義爲
	依山崖所建造的房屋。唐˙韓愈˙陪杜侍御遊湘西兩寺獨宿有題一首因獻楊常侍詩：「剖竹走泉源，開廊架崖广。」元˙袁桷˙次韻瑾子過梁山濼三十韻：「土屋危可緣，草广突如峙。」
	二一四部首之一。

如今萌典張冠李戴將「广」指向爲「廣」，十分不妥。

**Comment by kunki** [comment]
今天看到《敎育部重編國語辭典》的UI有重大更新，還原了大部分圖片字（如拼音、big5外字）。

其中就包括本issue提到的big5外字「广」。

請根據線上最新版的資料修復「广」的映射失誤。

參攷：http://dict.revised.moe.edu.tw/cgi-bin/cbdic/gsweb.cgi?o=dcbdic&searchid=W00000011008

**Comment by audreyt** [comment]
https://www.moedict.tw/%E5%B9%BF 已經根據線上最新版的資料修復。
