### ISSUE TITLE
「溼」

### ISSUE THREAD

**Issue by justinrleung** [audreyt/moedict-webkit#150]
在閩南語辭典中，查「溼」的時候，只顯示「澹」的條目。
![image](https://cloud.githubusercontent.com/assets/8852908/5693669/69921d94-98f6-11e4-80d0-2dd15a06d3d1.png)
但是按了「似」旁邊的「溼」之後，就會到「溼」的條目。
![image](https://cloud.githubusercontent.com/assets/8852908/5693678/f5c6f6fe-98f6-11e4-93d5-032cf5291001.png)
![image](https://cloud.githubusercontent.com/assets/8852908/5693685/3571d60c-98f7-11e4-9513-f83be4d0f042.png)
查「濕」的時候，就會顯示跟「溼」一樣的條目，只是「溼」換為「濕」。
![image](https://cloud.githubusercontent.com/assets/8852908/5693690/6384b4d8-98f7-11e4-8f9b-ab1723ab9a59.png)

我想這應該是因為去年十二月剛剛才修訂了用字 http://twblg.dict.edu.tw/holodict_new/compile1_8_1.jsp

**Comment by audreyt** [comment]
是的，這是上游資料的問題，在 http://twblg.dict.edu.tw/holodict_new 也有一樣的情況，請向上游 celinegan@mail.moe.gov.tw 反應，感謝！

**Comment by justinrleung** [comment]
我上面提出的問題就是用「溼」字查不到「溼」字的條目，但是可以從「澹」條目的「溼」字跳到「溼」字的條目，http://twblg.dict.edu.tw/holodict_new 就沒有這個問題；在 http://twblg.dict.edu.tw/holodict_new，「溼」字查到條目，而「濕」字才查不到任何條目。

詞目音讀：
![image](https://cloud.githubusercontent.com/assets/8852908/5848440/83d7fdc8-a1a6-11e4-917f-415704284416.png)
![image](https://cloud.githubusercontent.com/assets/8852908/5848452/abb0044e-a1a6-11e4-8877-b133d4240a8d.png)

![image](https://cloud.githubusercontent.com/assets/8852908/5848467/c4dfc076-a1a6-11e4-8822-3b93c91d4377.png)
![image](https://cloud.githubusercontent.com/assets/8852908/5848468/cc3080ea-a1a6-11e4-981d-e0ed33b7e674.png)

對應華語：
![image](https://cloud.githubusercontent.com/assets/8852908/5848499/0a93bed8-a1a7-11e4-8cb6-bf5ce58221ce.png)
![image](https://cloud.githubusercontent.com/assets/8852908/5848514/3df456b6-a1a7-11e4-9e1c-5645daae6f6e.png)

![image](https://cloud.githubusercontent.com/assets/8852908/5848591/f187fa02-a1a7-11e4-8ff4-a99c349d80c7.png)
![image](https://cloud.githubusercontent.com/assets/8852908/5848593/f7d0ad00-a1a7-11e4-8ffa-c57f9c5be1f7.png)

**Comment by viirya** [comment]
@justinrleung @audreyt 問題出在閩南語辭典的索引檔沒有更新。git repo 裡的檔案已經修正。
