### ISSUE TITLE
沒有自動執行 build-pinyin-lookup.pl

### ISSUE THREAD

**Issue by miaoski** [audreyt/moedict-webkit#155]
應該放在 make offline 跑嗎？
Dockerfile 還有 perl module 的 dependency 要顧。

**Comment by miaoski** [comment]
找不到 dict-revised.unicode.json

**Comment by miaoski** [comment]
$ perl build-pinyin-lookup.pl 
This looks weird: 欸 ?
This looks weird: 誒 ề

**Comment by audreyt** [comment]
或是讓它從 `a.txt` 取值？

**Comment by miaoski** [comment]
請看一下最新的 Dockerfile 那樣的結果似乎是 OK 的.
我沒仔細看為什麼會 this looks weird ，希望不會出問題.

**Comment by audreyt** [comment]
OK. 訊息是正常的，gugod 相當幽默。XD
http://logbot.gqv.tw/channel/g0v.tw/2015-01-15/213

**Comment by gugod** [comment]
https://github.com/gugod/moedict-webkit 在這個 fork 裡的 Makefile 已經調好。要不要先 merge 來？

那個 "This looks weird" 訊息其實告訴你「那些字的拼音看起來怪怪的」，是個 validation error，沒有被加到索引裡。也就是說目前無法用拼音找到「誒」和「欸」兩次。 :-p
