### ISSUE TITLE
Link Error When "Open link in new tab" 

### ISSUE THREAD

**Issue by mahiuchun** [audreyt/moedict-webkit#159]
Go to https://www.moedict.tw/ , click 國語辭典, ...部首表, then click "人".
This should show characters with radical 人 in 國語辭典.
( The address shows https://www.moedict.tw/@人 , but refreshing it makes the page blank!)

"Open link in new tab" (Chrome) for character 仁, we got to https://www.moedict.tw/@人#仁 which is blank.
I have to remove "@人" manually to see the definition of 仁.

**Comment by ethantw** [comment]
這個修正好像讓詞條的連結點擊後直接換頁，沒有正確觸發result更新事件？
