### ISSUE TITLE
客語例子

### ISSUE THREAD

**Issue by justinrleung** [audreyt/moedict-webkit#161]
我發覺在萌典，如果例子沒有華語解釋，就不會顯示。

例：在 (四 cai<sup>55</sup> 海 cai<sup>33</sup> 大 cai<sup>53</sup> 平 cai<sup>24</sup> 安 cai<sup>55</sup>)

萌典
![image](https://cloud.githubusercontent.com/assets/8852908/7009241/e43ddac0-dc66-11e4-9802-28824b2d2f2e.png)
教育部臺灣客家語常用詞辭典
![image](https://cloud.githubusercontent.com/assets/8852908/7009253/f7a1e12e-dc66-11e4-8e19-51c60ac78a8f.png)

萌典並沒有顯示「在於」和「自在」這兩個例子。

**Comment by audreyt** [comment]
感謝回報，已修復。

![2015-04-11 1 51 32](https://cloud.githubusercontent.com/assets/20723/7099214/24c37160-dfee-11e4-9895-6d0221cd058d.png)
