### ISSUE TITLE
Permanent Link for 部首

### ISSUE THREAD

**Issue by mahiuchun** [audreyt/moedict-webkit#162]
The URL for 部首表 is https://www.moedict.tw/@
The URL for 一部 is https://www.moedict.tw/@一 and so on

These URLs are not permanent links, though. Refreshing or re-entering these URLs would result in empty page.

**Comment by audreyt** [comment]
Thanks for the catch! It's now fixed (verified with Incognito window on https://www.moedict.tw/@%E6%B0%B4 etc)

**Comment by mahiuchun** [comment]
Thank you so much.
A remaining problem is that 部首表 itself and 水部 visited by clicking "國語辭典", "...部首表", "水" (applies to all other radicals as well, do not refresh) still suffer from #159 .

**Comment by audreyt** [comment]
Yes, and it actually affects all other links, like segmented words in definition too.

This has been fixed, but the fix needs more testing on IE9 and Safari before I can deploy it to production. I'll keep you posted in 24 hours.

**Comment by audreyt** [comment]
This is now deployed. Enjoy!

**Comment by mahiuchun** [comment]
Cool! Thank you!
