### ISSUE TITLE
萌典粉絲頁的推廣

### ISSUE THREAD

**Issue by a0kman** [audreyt/moedict-webkit#167]
萌典粉絲頁5/31已經建立了 網址如下:
https://www.facebook.com/pages/%E8%90%8C%E5%85%B8/1179288242097268?ref=bookmarks
或許可以置放在萌典的公告以及列出一個可以按讚的鈕讓萌典的使用者可以加入萌典粉絲團提供更多的互動和資訊

公告文案:
萌典成立FB粉絲團，歡迎各位使用者加入一起互動

**Comment by ethantw** [comment]
怎麼沒有專屬網址呢 XD

**Comment by a0kman** [comment]
https://www.facebook.com/MoeDic

抱歉忘記設定XD
