### ISSUE TITLE
人部7劃有一筆奇怪的資料

### ISSUE THREAD

**Issue by wayne930242** [audreyt/moedict-webkit#168]
https://www.moedict.tw/@%E4%BA%BA

第1筆。

![screenshot from 2015-06-22 17 12 29](https://cloud.githubusercontent.com/assets/5166321/8278905/e3cba55e-1901-11e5-8fad-d3c81cc6f35a.png)

**Comment by audreyt** [comment]
感謝，已於 moedict.org 修復，下次 moedict.tw 上線時會一併部署上去。

![2015-06-22 7 48 46](https://cloud.githubusercontent.com/assets/20723/8281154/be38966a-1917-11e5-95e8-5c0e7e6d478d.png)
