### ISSUE TITLE
Open Search

### ISSUE THREAD

**Issue by RexYuan** [audreyt/moedict-webkit#174]
你好，我是一個長期的萌典用戶（從高三準備考試就開始用了～），一直想要參與但是很廢，終於發現可以幫上忙的地方，想要做點貢獻！

這個 Open Search 在 YouTube 或 Dictionary.com 等支援內部搜索的網站都有用，可以讓一些瀏覽器整合這些搜尋；在 Chrome，這類網站只要在網址欄（Omni Box）打上網址在按下 `Tab` 或是 `Space` 就會進入客製搜尋，接下來直接打要搜尋的字就好了。
![imgur圖片喔](http://i.imgur.com/iWVbQ28.png)

這的功能是使用 Open Search 的格式知會瀏覽器的，詳情可以看他的 [Doc](http://www.opensearch.org/Specifications/OpenSearch/1.1#OpenSearch_description_document)。用的方式滿簡單，參考 Dictionary.com 的部分，關鍵在 HTML 的 `<head>` 加上這行：
```HTML
<link rel="search" type="application/opensearchdescription+xml" href="http://dictionary.reference.com/opensearch_desc.xml" title="Dictionary.com"/>
```
另外他 `href` 到的檔案，這邊的例子就是 http://dictionary.reference.com/opensearch_desc.xml 內容是這樣：
```XML
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
<ShortName>Dictionary.com</ShortName>
<Description>Look it up at Dictionary.com</Description>
<Image height="16" width="16" type="image/x-icon">
http://static.sfdict.com/en/i/dictionary/newserp/favicon.ico
</Image>
<Url type="text/html" method="get" template="http://dictionary.reference.com/browse/{searchTerms}?r=75&src=ref&ch=dic"/>
</OpenSearchDescription>
```
這裏的重點在 `<Url>` 裡面的 `template` attribute，放上可以 query 的網址，然後把 query 的內容改成 `{searchTerms}` 就可以了。

在萌典的例子裡，這邊可能是 `https://www.moedict.tw/{searchTerms}`。如果成功的話，在 Chrome Settings 的 Manage search engines 裡會發現他已經記錄起來了，可能長這樣：
![又是imgur的圖](http://i.imgur.com/2Nhf4KU.png)
然後嘗試在網址欄打上 `moedict.tw` 再按下 `Space` 應該就能夠直接搜尋了：
![再一張imgur圖](http://i.imgur.com/nrSd7FW.png)
打完之後按下 `Enter` 就會成功了！

如果你們覺得這個功能不錯，我可以直接開 Pull Request，快速簡單加上這個到[裡面](https://github.com/audreyt/moedict-webkit/blob/master/index.html)跟開那個 XML 檔喔！

**Comment by audreyt** [comment]
感謝！我們有 https://www.moedict.tw/opensearch/moedict.xml (源碼： https://github.com/audreyt/moedict-webkit/blob/master/opensearch/moedict.xml ），但沒有加上 `link rel="search"` — 請直接編輯 https://github.com/audreyt/moedict-webkit/blob/master/index.jade 加上這個連結，如果 moedict.xml 需要調整，也歡迎直接修正！
