### ISSUE TITLE
[Question] Sentence Splitting

### ISSUE THREAD

**Issue by gsklee** [audreyt/moedict-webkit#177]
``` html
<span class="def" data-reactid=".1j5vghb7n5s.$0.7.$0.0.$0.0.$0">
<a href="./位於">位於</a>
<a href="./安徽省">安徽省</a>
<span class="punct"><a href="./西北">西北</a>，</span>
<a href="./淮河">淮河</a>
<span class="punct"><a href="./南岸">南岸</a>。</span>
</span>
```

@audreyt How is this achieved? Does it use some 3rd party library or...?

**Comment by caasi** [comment]
I don't know exactly how @audreyt did it, but you may like to check [L18][0] and [L178][1] of `server.ls`.

[0]: https://github.com/audreyt/moedict-webkit/blob/master/server.ls#L18
[1]: https://github.com/audreyt/moedict-webkit/blob/master/server.ls#L178

**Comment by gsklee** [comment]
Wow... I guess I got it. So basically `lenToRegex.json` has all the available entry names put in one place and that can be used to parse and split sentence.

**Comment by caasi** [comment]
And `lenToRegex.*` are created by `json2prefix.ls` and `autolink.ls`.

**Comment by kcwu** [comment]
close since the question is answered.
