### ISSUE TITLE
Using a public CDN service or not?

### ISSUE THREAD

**Issue by PeterDaveHello** [audreyt/moedict-webkit#184]
Hi @audreyt,

I wonder if you would like to [es5-shim](https://cdnjs.com/libraries/es5-shim) and [jquery-ui](https://cdnjs.com/libraries/jqueryui) theme on CDNJS, which is using Cloudflare's service with super fast networking, and all the files are minified, so maybe can speed up the loading time, since I saw that https://www.moedict.tw/ is using fastly CDN(*I guess, hope I didn't guess wrong*), so not sure what's your idea, if you are paying for the CDN by yourself, this can also help decrease the usage of it so that can save some money.

PS, note that jquery ui theme is not on CDNJS yet, but I'm not working on it now, since I want to use zopfli compression in the PNG image internal, and also optimize every image on the CDN, which can extremely decrease the file size to speed up the loading time, it will take a while, but feel free to decide using or not, that's independent.

Best,
Peter

**Comment by audreyt** [comment]
We use `Fast.ly` indeed. I'm paying the CDN mostly for the HTTPS processing.

CloudFlare used to have a lot of issues during Taiwan nighttime with HiNet users due to lack of peering bandwidth, I'm happy to switch back to it if (and only if) that is resolved.

**Comment by PeterDaveHello** [comment]
I heard about the issue with HiNet, though I have no problem with that, I'll check it out again, another pros to using CDNJS is that cloudflare supports both SPDY and HTTP/2, which can totally decrease the loading time, seems fastly support neither, I thought most of the CDN services support one of them.

**Comment by PeterDaveHello** [comment]
CloudFlare now has a data center in Taiwan for a while, maybe the issue can be treated as "solved", what do you think @audreyt ?

**Comment by audreyt** [comment]
Yeah I saw your blog post. :-)

https://amis.moedict.tw/#;ci%27im is on CloudFlare. If everything looks good to you I'll switch back to CloudFlare soon.

**Comment by PeterDaveHello** [comment]
Looks good for me, I wonder if you would like to put all the site behind CloudFlare directly, or we can use some libs on CDNJS? I believe CDNJS can be faster than just use pull origin CDN on CloudFlare.

**Comment by audreyt** [comment]
How would it be faster if it's served on the same edge POP? (Not a rhetorical question; really curious)

**Comment by PeterDaveHello** [comment]
cdnjs.cloudflare.com is more like a push zone which doesn't need to connect to the server behind the CDN, and though I'm not sure what's the plan on CloudFlare you would like to choose, as you can see, the pro plan is claimed to have better performance, so there maybe something like QoS, I'm not working at CloudFlare so cannot really know the detail, at least, one thing I'm use is that using CDNJS will have chances to share the caches with others since it's a public CDN service, right?

**Comment by audreyt** [comment]
Right. I'm on CloudFlare Pro and so should have the ~same QoS guarantees.

Another concern for CDNJS is that we currently use the same application code as the Cordova (Mobile App) version, which is best kept in the offline bundle instead of connecting to an external CDNJS site.

**Comment by PeterDaveHello** [comment]
Oh, okay, if so, I'm okay with both using Fastly and CloudFlare, no problem!

**Comment by PeterDaveHello** [comment]
Not so related, but just found that fastly has open source plan, maybe you can consider to apply it for moedit :)
-> https://www.fastly.com/open-source

**Comment by audreyt** [comment]
It's OK, I've switched off Fastly and moved to Cloudflare. :-)
