### ISSUE TITLE
𦰡(十六進位:U+26C21 十進位:158753) 找不到

### ISSUE THREAD

**Issue by kiang** [audreyt/moedict-webkit#185]
網址： https://www.moedict.tw/%F0%A6%B0%A1

因為台南有個 𦰡拔里

**Comment by audreyt** [comment]
感謝回報，經查上游 http://dict.revised.moe.edu.tw/ 也沒有，收字問題請向 onile@mail.naer.edu.tw 反映~

**Comment by kiang** [comment]
附上回信供參考

> 發文日期：中華民國105年3月23日
> 發文字號：教研譯字第1051300720號
> 
> 您好。您於105年3月15日寄送至本院語教辦公室意見信箱之來信已收悉，有關所詢問題，謹說明如下：
> 辭典所收字詞大致以一般語文使用為主，教育部五部國語字、辭典，因編輯目的、服務對象不同，而各有特定的收錄範圍，您可參考本院網站之各典簡介說明（ http://www.naer.edu.tw/files/11-1000-962.php?Lang=zh-tw ）。來函提及的《重編國語辭典修訂本》因屬辭典性質，故主要收錄複詞，不收過於罕用的字，故未收錄所詢上為「艹」下為「那」之字。
