### ISSUE TITLE
四縣客語白話字

### ISSUE THREAD

**Issue by glll4678** [audreyt/moedict-webkit#188]
在偏好設定裡增加「四縣客語白話字」（顯示／不顯示），示意圖：
![2016-06-27 14 48 05](https://cloud.githubusercontent.com/assets/6016585/16371254/f1061692-3c77-11e6-8f8c-d1293678a00d.png)
若勾選「顯示」，於「四」左方增加「白」，示意圖：
![2016-06-27 14 58 33](https://cloud.githubusercontent.com/assets/6016585/16371256/f53547e2-3c77-11e6-8e1c-463ae00d3ec3.png)

對照表：

| 客家語拼音方案 | 客語白話字 |
| ------------- | ------------- |
| b | p |
| p | ph |
| d | t |
| t | th |
| g | k |
| k | kh |
| j | ch |
| q | chh |
| z | ch |
| c | chh |
| x | s |
| i- | y- |
| -i | -i |
| i (單拼) | yi |
| ii | ṳ |
| ua | oa |
| ue | oe |
| 24 | â |
| 11 | à |
| 31 | á |
| 55 | a |
| 2 | a |
| 5 | a̍ |

聲調符號位置: a>u>o>i>i>>ṳ>n>m (例外: oa 標在 o 上)

**Comment by audreyt** [comment]
感謝~ 下次萌典松來實作看看，或是如果能先用 JavaScript (或任一種程式語言) 實作也很歡迎。

**Comment by glll4678** [comment]
| 客家語拼音方案 | 客語白話字 |
| ------------- | ------------- |
| t | th |
| p | ph |
| k | kh |
| c | chh |
| b | p |
| d | t |
| g | k |
| j | ch |
| q | chh |
| x | s |
| z | ch |
| ii | ṳ |
| ua | oa |
| ue | oe |
| i- | y- |
| y (單拼)| yi |

最後兩行：
在頭的「i」，全變「y」
「y」單獨出現時，變「yi」

**Comment by audreyt** [comment]
Deployed on http://www.moedict.org/#:%E7%99%BC%E8%8A%BD — moedict.tw to be updated later
