### ISSUE TITLE
請問是否可以使用 API 製作國語字典的 app?

### ISSUE THREAD

**Issue by joe528** [audreyt/moedict-webkit#191]
如果我想做一個 app 可以當作國語字典，是否可用 moedict API 查詢，例如：

https://www.moedict.tw/raw/%E8%90%8C

將其返回的內容顯示給使用者看？

是否有和版權 issue 或者需要特別註明什麼？

**Comment by ethantw** [comment]
當然可以。請依關於頁面注明的授權方式使用即可。

<https://www.moedict.tw/about.html>
