### ISSUE TITLE
教育部國語字典「狼」定義有修正。

### ISSUE THREAD

**Issue by Austin7788** [audreyt/moedict-webkit#194]
查尋萌典，「狼」，的第二點定義：

「忠」國古代的少數民族之一。約聚集在大陸地區廣東、廣西兩省的交界處。

裡面的「忠」國，是個筆誤。
之前在教育部那裡也是這麼寫的，但現已更正。我不知道怎麼編輯萌典。但可以需要有人去那裡改一個字。

**Comment by audreyt** [comment]
您好，這是來自 dict-revised.json line 1750097:

https://github.com/g0v/moedict-data/blob/master/dict-revised.json <https://github.com/g0v/moedict-data/blob/master/dict-revised.json>

因為教育部採 ND（禁止改作）授權，所以我們只能在公開版本更新後，才能自動由 moedict-process 取得修正：

http://resources.publicense.moe.edu.tw/dict_reviseddict_download.html <http://resources.publicense.moe.edu.tw/dict_reviseddict_download.html>
