### ISSUE TITLE
Unicode 安裝程式

### ISSUE THREAD

**Issue by ky7749** [audreyt/moedict-webkit#200]
你好，

NSIS 已發行 3.0 版本，支援 UNICODE。
可否考慮更新 Windows 的安裝檔？

謝謝。

**Comment by audreyt** [comment]
Cc @racklin

**Comment by ky7749** [comment]
忘記了說，現在的安裝檔案是以 NSIS 2.46 版建立（不支援 UNICODE)。如果控制台＞地區語言的「非 UNICODE 程式的語言」不是設定為中文，會出亂碼。使用 NSIS 3.0 會好些（安裝腳本可能要作少少修改）。

**Comment by racklin** [comment]
@ky7749 @audreyt 好的，今天試著用 NSIS 3.0 重新打包安裝程式。

**Comment by racklin** [comment]
@ky7749 已經利用 NSIS 3.0 重新打包，並支援正體中文及英文二個語系安裝。 已更新原下載檔案。
謝謝建議。
