### ISSUE TITLE
更新客語資料

### ISSUE THREAD

**Issue by caasi** [audreyt/moedict-webkit#213]
萌典粉絲頁中，王先生、林先生與康先生反應客語資料需要更新，其中王先生提到 105 年有修訂公告： http://hakka.dict.edu.tw/hakkadict/file/revise1050526-2.pdf

**Comment by audreyt** [comment]
=> https://github.com/g0v/moedict-data-hakka/issues/4

歡迎填坑，我可能要等大松或十月萌典松時才會有空。
