### ISSUE TITLE
chrome 呈現台文輕聲調號有問題

### ISSUE THREAD

**Issue by wildjcrt** [audreyt/moedict-webkit#45]
chrome 上的輕聲跑到「物」那邊去了
![2013-08-02 11 14 03](https://f.cloud.github.com/assets/175151/901745/3649ee44-fb86-11e2-957d-553adde199eb.png)

FF 正常
![2013-08-02 11 14 48](https://f.cloud.github.com/assets/175151/901767/7aaa8d50-fb86-11e2-9389-2fcd0b65730a.png)

link: [http://moedict.org/#!植物](http://moedict.org/#!植物)

**Comment by drott** [comment]
Corresponding Blink issue is fixed. Likely cause is switching to HarfBuzz on Mac in Chrome M40.

**Comment by audreyt** [comment]
Confirmed the fix. The combining glyph is positioned slightly toward the right compared to Firefox, but it's well acceptable and a huge improvement over the previous treatment. Thanks! :rainbow:

**Comment by drott** [comment]
Agree on the "slight right" positioning - however, the glyph that is used in the bug report is COMBINING DOT ABOVE RIGHT. When the string of BOPOMOFO FINAL LETTER T and the DOT ABOVE RIGHT is rendered in other fonts, for example by just pasting it into TextEdit on Mac, the dot is placed further right. This might be an issue with the moedict font. If you have more details, or reason to believe, this placement is wrong, please file a new issue on Blink and CC dominik.rottsches@intel.com - Thanks.

**Comment by ethantw** [comment]
@audreyt: I have asked this question once. But can you tell me again which character is semantically correct? `U+030d` or `U+0358`. If it's the first one, maybe we should use it altogether on Zhuyin and Romanization.

**Comment by audreyt** [comment]
030d is correct, but WebKit (on iOS and Android) had problems with them in 2013 — https://plus.google.com/112631966921288326739/posts/gn2qP6FR6XQ — If they are no longer relevant we can switch back to 030d.

**Comment by pcchen** [comment]
It should be U+0358.

**Comment by audreyt** [comment]
OTOH, for Extended BPMF we should continue to use 0358.

**Comment by ethantw** [comment]
@audreyt, @pcchen: Thanks! So, Yang-checked tones should be positioned ‘slightly right’ in Extended Zhuyin?

**Comment by audreyt** [comment]
台(87)語字第八七ＯＯＯ五七七號 did not provide positional placement suggestions, but 吳守禮's bitmap font has it rendered thus:

![a0e7](https://cloud.githubusercontent.com/assets/20723/7276811/f44f404a-e93e-11e4-9930-e09c7f6f8d2f.png)

That's also what I saw in printed books. So ideally it should be a dot and pointed exactly in the middle.

**Comment by ethantw** [comment]
Then maybe it's better we use `U+0307` (COMBINING DOT ABOVE)? It is also the character used in the entry of Wikipedia. 

<http://zh.wikipedia.org/wiki/臺灣方音符號>

**Comment by pcchen** [comment]
中文注音符號的輕聲用哪個 glyph?

**Comment by audreyt** [comment]
輕聲是 U+02D9 Dot Above。

I'm OK to switch to U+0307.

**Comment by ethantw** [comment]
> 輕聲用哪個 glyph?

國語的輕聲和漢語典型的四聲（平上去入）好像不太一樣。「因為輕聲用dot above，所以陽入韻也該用(combining) dot above」不曉得邏輯上是否正確。

方音符號因為我手邊資料不多，可能在CLReq上有遺漏，希望各位可以幫忙review一下3.3.3節下的a、b和c小節。 <http://w3c.github.io/clreq/zh/#positioning_of_zhuyin>

**Comment by audreyt** [comment]
Liz Lin 提出「ㄉ加輕聲符號整個縮小」的意見，並舉出楊秀芳老師的書上看到實際用法也是這樣。我看到的紙本也是這樣處理無誤。

**Comment by ethantw** [comment]
> 「ㄉ加輕聲符號整個縮小」

意思是下圖的陽入韻符號應保持在灰色字幅裡面？這與其他的附加符號處理（比如拉丁字母）都不太一樣呢。

![力 with Zhuyin](http://w3c.github.io/clreq/zh/images/zhuyin-2-4-two-symbol-lik.svg)
